[build] 
  publish = "public"
  command = "hugo"
[context.production.environment]
  HUGO_VERSION = "0.74.3" # if older, use format: 0.69.2 (no trailing zero)
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"
[context.branch-deploy.environment]
  HUGO_VERSION = "0.74.3" # if older, use format: 0.69.2 (no trailing zero)
[context.deploy-preview.environment]
  HUGO_VERSION = "0.74.3"
  
[frontmatter]
date = ["publishDate","date", "lastmod"]
lastmod = ["publishDate","lastmod", "date" ]
publishDate = ["publishDate", "date"]
expiryDate = ["expiryDate"]